/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertPopup: typeof import('./src/components/alertPopup.vue')['default']
    BackHeader: typeof import('./src/components/backHeader.vue')['default']
    ChipOption: typeof import('./src/components/chipOption.vue')['default']
    CommentBanner: typeof import('./src/components/commentBanner.vue')['default']
    PopupWindow: typeof import('./src/components/popupWindow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
